### ISSUE TITLE
Inquiry Regarding Code Release for Dysen-VDM

### ISSUE THREAD

**Issue by Njasa2k** [scofield7419/Dysen#1]
I'm intrigued by your recent paper on text-to-video synthesis. I noticed your GitHub repository for the code, but it seems to be empty at the moment. I'm eager to explore the implementation details and was wondering if you could provide an update on when the code might be available.

**Comment by Bailey-24** [comment]
why empty? Who eats it?

**Comment by scofield7419** [comment]
Hello, thanks for everybody's attention & sorry for such delay (you know, for the peer-reviewing consideration).
Now the codes released.
